# Generated by Django 2.1.5 on 2019-03-15 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_title', models.CharField(max_length=100)),
                ('essy_published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published')),
                ('essay_content', models.TextField()),
            ],
        ),
    ]
