# Generated by Django 2.2.1 on 2019-07-21 09:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EssayCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=100)),
                ('category_summary', models.CharField(max_length=200)),
                ('category_slug', models.CharField(default=1, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='EssaySeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_title', models.CharField(max_length=100)),
                ('series_summary', models.CharField(max_length=200)),
                ('series_slug', models.CharField(default=1, max_length=50)),
                ('category_title', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.EssayCategory', verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('essay_title', models.CharField(max_length=100)),
                ('essy_published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published')),
                ('essay_content', models.TextField()),
                ('essay_slug', models.CharField(default=1, max_length=50)),
                ('series_title', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.EssaySeries', verbose_name='Series')),
            ],
        ),
    ]
