# Generated by Django 2.1.5 on 2019-03-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssaySeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_title', models.CharField(max_length=100)),
                ('series_summary', models.CharField(max_length=200)),
                ('series_slug', models.CharField(default=1, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
    ]
