# Generated by Django 2.1.5 on 2019-03-15 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_essayseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='series_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.EssaySeries', verbose_name='Series'),
        ),
        migrations.AddField(
            model_name='essay',
            name='tutorial_slug',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
