# Generated by Django 2.1.5 on 2019-03-15 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190316_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essay',
            old_name='tutorial_slug',
            new_name='essay_slug',
        ),
    ]
