# Generated by Django 2.2.1 on 2019-07-21 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190316_0140'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EssayCategory',
        ),
    ]
