# Generated by Django 2.2.1 on 2019-07-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_essaycategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(max_length=100)),
                ('category_summary', models.CharField(max_length=200)),
                ('category_slug', models.CharField(default=1, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
