# Generated by Django 2.2.1 on 2019-07-21 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_essaycategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayseries',
            name='category_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.EssayCategory', verbose_name='Category'),
        ),
    ]
