# Generated by Django 2.2.1 on 2019-07-21 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_essayseries_category_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essay',
            old_name='essy_published',
            new_name='essay_published',
        ),
    ]
