# Generated by Django 2.2.3 on 2019-07-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='essay_image',
            field=models.ImageField(blank=True, default='/static/main/images/sample-1.jpg', null=True, upload_to='images/essay/'),
        ),
    ]
