# Generated by Django 2.2.3 on 2019-07-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_essay_essay_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='essay_image',
            field=models.ImageField(blank=True, default='images/sample-1.jpg', null=True, upload_to='images/essay/'),
        ),
    ]
