# Generated by Django 2.2.3 on 2019-07-21 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190722_0023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
