# Generated by Django 2.2.3 on 2019-07-21 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_essaycategory_essay_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essaycategory',
            old_name='essay_image',
            new_name='category_image',
        ),
    ]
