# Generated by Django 2.2.1 on 2019-07-23 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_essayseries_series_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='category_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.EssayCategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='essay',
            name='essay_content',
            field=models.TextField(help_text='Write here your message!'),
        ),
    ]
