# Generated by Django 2.2.1 on 2019-07-23 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190724_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='category_title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.EssayCategory', verbose_name='Category'),
        ),
    ]
