# Generated by Django 2.2.1 on 2019-07-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190724_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='essay_contributor',
            field=models.CharField(default='Admin', max_length=50),
        ),
    ]
