# Generated by Django 2.2.1 on 2019-07-26 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_essay_essay_contributor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essay',
            name='essay_contributor',
        ),
    ]
