# Generated by Django 2.2.1 on 2019-07-26 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0019_remove_essay_essay_contributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='essay_contributor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
