# Generated by Django 2.2.1 on 2019-07-29 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Feedback Time'),
        ),
    ]
