# Generated by Django 2.2.3 on 2019-08-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20190730_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='essay_summary',
            field=models.CharField(blank=True, help_text='Write summary here!', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_user_id',
            field=models.EmailField(max_length=254, verbose_name='Email ID'),
        ),
    ]
